version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: sob
    ports:
      - "5422:5432"
    volumes:
      - ./app:/backend/app


  # socket:
  #   build: ./
  #   container_name: web_socket
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./app:/backend/app

  # alembic:
  #   build: ./
  #   command: alembic upgrade head
  #   volumes:
  #     - ./app:/backend/app
  #   depends_on:
  #     - db
