version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: sob
    ports:
      - "5422:5432"


  socket:
    build: ./
    container_name: web_socket
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./app:/app
