version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: sob
    ports:
      - "5422:5432"

  socket:
    build: ./
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    container_name: web_socket
    ports:
      - "8000:80"
