"""V0.2

Revision ID: 5c0b0c74e20f
Revises:
Create Date: 2024-04-02 20:56:28.206553

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5c0b0c74e20f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
