"""Fix model Room

Revision ID: 7b0791b8adc4
Revises: 5c0b0c74e20f
Create Date: 2024-04-02 21:06:57.440235

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b0791b8adc4"
down_revision: Union[str, None] = "5c0b0c74e20f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("room", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "room", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "room", type_="foreignkey")
    op.drop_column("room", "user_id")
    # ### end Alembic commands ###
