"""Fix model Room 0.3

Revision ID: 9f0ed45d21ff
Revises: ad80290f2770
Create Date: 2024-04-02 21:26:30.261761

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9f0ed45d21ff"
down_revision: Union[str, None] = "ad80290f2770"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
