"""Fix model Room 0.2

Revision ID: ad80290f2770
Revises: 7b0791b8adc4
Create Date: 2024-04-02 21:25:16.409142

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ad80290f2770"
down_revision: Union[str, None] = "7b0791b8adc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
