"""Create message model 0.4

Revision ID: afe905900a0a
Revises: 207a9fa7c95b
Create Date: 2024-04-07 22:51:14.252635

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe905900a0a"
down_revision: Union[str, None] = "207a9fa7c95b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("message_message_key", "message", type_="unique")
    op.drop_constraint("message_user_name_key", "message", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("message_user_name_key", "message", ["user_name"])
    op.create_unique_constraint("message_message_key", "message", ["message"])
    # ### end Alembic commands ###
