"""Create message model

Revision ID: db93342d8c95
Revises: 9f0ed45d21ff
Create Date: 2024-04-07 20:04:20.948157

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "db93342d8c95"
down_revision: Union[str, None] = "9f0ed45d21ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
